---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx
  labels: 
    app: nginx
    env: test
spec: 
  minReadySeconds: 5
  replicas: 4
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels: 
        app: nginx
        env: test
    spec:
      containers: 
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
              protocol: TCP