---
apiVersion: v1
kind: Service
metadata: 
  name: my-svc
spec:
  type: NodePort
  selector:
    app: nginx
    env: test
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 80
      targetPort: 80