---
apiVersion: v1
kind: Pod
metadata:
  name: initc1
spec:
  initContainers:
    name: int
    image: alpine:3
    command:
      - "sleep"
      - "5"
---
apiVersion: v1
kind: Pod
metadata:
  name: initc2
spec:
  initContainers:
    name: int
    image: alpine:3
    command:
      - "sleep"
      - "5"
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    name: init
    image: nginx:1.25
    ports: 80
    command:
      - "sleep"
      - "5"
      
      