---
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  initContainers:
    - name: initc1
      image: alpine:3
      command:
        - "sleep"
        - "30"
    - name: initc2
      image: alpine:3
      command:
        - "sleep"
        - "30"
  containers:
    - name: appcont
      image: nginx:1.25
      ports: 
        - containerPort: 80
          protocol: TCP

      