---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: alpine-jenkins
  labels:
    app: jenkins
    env: test
spec:
  minReadySeconds: 3
  replicas: 5
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata: 
      name: alpine
      labels: 
        app: jenkins
        env: test
    spec:
      initContainers:
        - name: alpine
          image: alpine:3
          command: 
            - "ping"
            - "-c"
            - "4"
            - "google.com"
  
      containers:
        - name: junk
          image: jenkins/jenkins:jdk11
          ports: 
            - containerPort: 8080
              protocol: TCP

