---
apiVersion: v1
kind: Pod
metadata:
  name: restrt-polcy
spec:
  containers:
    name: httpd
    image: apache:2
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: rstrt-polcy
spec:
  containers:
    name: Raspberry-Pi
    image: alpine:3
  restartPolicy: OnFailure