---
apiVersion: v1
kind: Pod
metadata:
  name: restrt-polcy
spec:
  containers:
    - name: restrt-never
      image: apache:2
      command:
        - "sleep"
        - "2"
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: rstrt-nopolcy
spec:
  containers:
    - name: raspberrypi
      image: alpine:3
      command:
        - "sleep"
        - "2"
  restartPolicy: OnFailure